/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);

extern void tearDown(void);

extern void testMatrixCreation(void);

extern void testMatrixMul();




/*=======Test Reset Option=====*/
void resetTest(void);

void resetTest(void) {
    tearDown();
    setUp();
}


/*=======MAIN=====*/
int main(void) {
    UnityBegin("test/tests/testTuple.c");
    RUN_TEST(testMatrixCreation, 1);
    RUN_TEST(testMatrixMul,1);


    return (UnityEnd());
}